<Project Sdk="Microsoft.NET.Sdk">

  <!-- Copyright (c) Microsoft Corporation.
       Licensed under the MIT license. -->

  <ItemGroup>
    <ProjectReference Include="..\Ksr.Local.Core\Ksr.Local.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ksr.Local.Kusto.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Kusto.Data" Version="14.2.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
